title: Amandeep Singh Khanna
baseurl: ''
url: amandeepsinghkhanna.com
google_analytics: G-PYQ4ZZQ3QD
markdown: kramdown
include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-paginate
permalink: '/:categories/:title/'
paginate: 10
jekyll-relative-links:
  enabled: true
  collections: true
collections:
  teaching_notes:
    output: true
    permalink: '/:collection/:name/'
