title: Amandeep Singh Khanna
baseurl: ''
url: amandeepsinghkhanna.com
google_analytics: G-PYQ4ZZQ3QD
markdown: kramdown
include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-relative-links
permalink: '/:categories/:title/'
paginate: 10

collections:
  posts:
    output: true
    permalink: '/:collection/:name/'
  llm_prompt_categories:
    output: true
    permalink: '/:collection/:name/'
  teaching_notes:
    output: true
    permalink: '/:collection/:name/'
