title: Amandeep Singh Khanna
baseurl: ""
url: "amandeepsinghkhanna.com"
google_analytics: G-PYQ4ZZQ3QD

markdown: kramdown
include:
  - _pages

sass:
  sass_dir:     _sass
  style:        compressed

plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:title/:year-:month-:day/
paginate:       10
